[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
extra_scripts = pre:scripts/load_wifi_env.py

monitor_speed = 115200

lib_deps =
    majicdesigns/MD_Parola
    majicdesigns/MD_MAX72XX
