[platformio]
default_envs = esp32dev

[env]
platform = espressif32
board = esp32dev
framework = arduino
board_build.filesystem = littlefs
extra_scripts = pre:scripts/load_wifi_env.py

monitor_speed = 115200
upload_speed = 115200

lib_deps =
    majicdesigns/MD_Parola
    majicdesigns/MD_MAX72XX

[env:esp32dev]

[env:esp32dev_ota]
upload_protocol = espota
upload_port = milluboard.local
